Local Test Environment
Csardelacal/PHPAuthServer pull request #34
Opened 2022-01-14 18:05 UTC by pcgames3112

2022-01-14 22:06 UTC, Csardelacal commented on index.php
> +error_reporting(0);
I think I'd get rid of this. Since we do actually want the system to issue us warnings when we mess stuff up

2022-01-14 22:07 UTC, Csardelacal requested changes
I think the error reporting needs to be reset to match the server's config.

2022-01-15 07:25 UTC, pcgames3112 commented on index.php
> +error_reporting(0);
Removed it

2022-01-15 08:53 UTC, Csardelacal approved these changes
Perfect!

2022-01-15 08:56 UTC, merged